# Generated by Django 3.0.6 on 2020-05-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admit_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
