# Generated by Django 3.0.6 on 2020-05-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200520_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(max_length=10)),
                ('course_name', models.CharField(max_length=15)),
                ('fees', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='admit_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='zip_code',
            field=models.CharField(max_length=6),
        ),
    ]
