# Generated by Django 3.0.6 on 2020-05-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200522_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='fees',
        ),
    ]
