# Generated by Django 3.0.6 on 2020-05-22 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_course_fees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
