# Generated by Django 3.0.6 on 2020-05-22 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
